fsm_AI_gen.avr.c: angfsm_gen_avr_AI.h
dot_AI_1.dot: fsm_AI_gen.h
angfsm_gen_avr_AI.h: io_hub.host
	./$< --ang-gen avr --ang-dot AI.dot
	mv angfsm_gen_avr_AI.c fsm_AI_gen.avr.c

view: AI.view
png: AI.png
svg: AI.svg

%.view: %.dot
	dot -Txlib $<
%.png: %.dot
	dot -Tpng $< > $@
%.svg: %.dot
	dot -Tsvg $< > $@
