fsm : mainFsm.dot chargeBall.dot getSamplesFsm.dot chuteFsm.dot
	dot -Tpng -o mainFsm.png mainFsm.dot
	dot -Tpng -o chargeBall.png chargeBall.dot
	dot -Tpng -o getSamplesFsm.png getSamplesFsm.dot
	dot -Tpng -o chuteFsm.png chuteFsm.dot