CFLAGS = -O2 -Wall

all: prgm exe dot png 

prgm: getSamplesFsm.fsm getSamplesFsm.conf
	python ../../../tools/dfagen/dfagen.py -o c -d $< -c getSamplesFsm.conf -p getsamples 

exe: prgm 

dot: getSamplesFsm.fsm getSamplesFsm.conf
	python ../../../tools/dfagen/dfagen.py -o dot -d $< -c getSamplesFsm.conf -p getsamples

png: getsamples.dot
	dot -Tpng -o getsamples.png getsamples.dot

clean:
	rm -f getsamples.h
	rm -f getsamples_cb.h
	rm -f getsamples.dot
	rm -f getsamples.png
	rm -f getsamples.c
