BASE = ../../../..
HOST_PROGS = test_motor_model
test_motor_model_SOURCES = test_motor_model.c
MODULES = motor/motor_model
# -O2 : speed
# -Os : size
OPTIMIZE = -O2
HOST_LIBS = -lm

include $(BASE)/make/Makefile.gen
