BASE = ../../../..
AVR_PROGS = test_twi_usi
test_twi_usi_SOURCES = test_twi_usi.c
MODULES = twi
CONFIGFILE = avrconfig.h
# atmega8, atmega8535, atmega128...
AVR_MCU = attiny85
# -O2 : speed
# -Os : size
OPTIMIZE = -Os

include $(BASE)/make/Makefile.gen
