BASE = ../../..
HOST_PROGS = test_path
test_path_SOURCES = test_path.c
MODULES = path math/fixed utils
CONFIGFILE = avrconfig.h
# atmega8, atmega8535, atmega128...
AVR_MCU = atmega128
# -O2 : speed
# -Os : size
OPTIMIZE = -O2

include $(BASE)/make/Makefile.gen
